# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- devel

pool:
  vmImage: ubuntu-latest

steps:
- task: BatchScript@1
  inputs:
    filename: 'scripts/gogetcookie.sh'
- task: make tools
- task: export GOFLAGS=-mod=vendor
- task: export GO111MODULE=on
- task: pwd
- task: go version
- task: echo $GOPATH

- task: Go@0
  inputs:
    command: 'build'

- task: Go@0
  inputs:
    command: 'test'
